/*
 * Data version: 240221_080721
 *
 * Copyright (C) 2017-2024 Texas Instruments Incorporated - http://www.ti.com/
 * ALL RIGHTS RESERVED
 */
#ifndef SOC_AM62LX_CLOCK_LIMITS_H
#define SOC_AM62LX_CLOCK_LIMITS_H


#define SOC_CLOCK_VALUES_RANGE_ID_MAX 87

#define SOC_PLL_TABLE_RANGE_ID_MAX 12

#define SOC_CLOCK_FREQ_DEFAULTS_RANGE_ID_MAX 5

#define SOC_CLOCK_DATA_RANGE_ID_MAX 178

#define SOC_CLOCK_RANGES_ID_MAX 5

#define SOC_CLOCKS_RANGE_ID_MAX 178

#define HOST_RANGE_ID_MAX 1

#endif /* SOC_AM62LX_CLOCK_LIMITS_H */
