/*
 * Data version: 240221_080721
 *
 * Copyright (C) 2017-2024 Texas Instruments Incorporated - http://www.ti.com/
 * ALL RIGHTS RESERVED
 */
#ifndef SOC_AM62LX_DEVICE_LIMITS_H
#define SOC_AM62LX_DEVICE_LIMITS_H


#define PM_DEVGRP_RANGE_ID_MAX AM62LX_PM_DEVGRP_RANGE_ID_MAX
#define SOC_DEVICES_DATA_ARR_RANGE_ID_MAX 166

#define SOC_DEVICES_RANGE_ID_MAX 166

#define SOC_MULTIPLE_DOMAINS_RANGE_ID_MAX 1


#endif /* SOC_AM62LX_DEVICE_LIMITS_H */
