BL31_SOURCES		+=	\
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_handler.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_adpllm.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_dev.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_div.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_fixed.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_gate.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_mux.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_pll_16fft.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_pllctrl.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_pll_deskew.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/pll.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/osal_wrapper.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/clk_wrapper.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/ilog.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/div64.c    \
				${PLAT_PATH}/am62l/scmi/drivers/clock/notifier.c    \
				drivers/delay_timer/delay_timer.c	\
